---
resources:
  - name: source
    type: git
    source:
      uri: 'git@github.com:mattcl/ganttify.git'
      branch: master
      private_key: ((clone_key))

jobs:
- name: py27
  plan:
  - get: source
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: 'python:2.7'}
      inputs:
        - name: source
      run:
        path: source/ci/test.sh

- name: py35
  plan:
  - get: source
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: 'python:3.5'}
      inputs:
        - name: source
      run:
        path: source/ci/test.sh

- name: py36
  plan:
  - get: source
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: 'python:3.6'}
      inputs:
        - name: source
      run:
        path: source/ci/test.sh
