---
resources:
  - name: source
    type: git
    source:
      uri: 'git@github.com:mattcl/ganttify.git'
      branch: master
      private_key: ((clone_key))

jobs:
- name: unit
  plan:
  - get: source
    trigger: true

  - aggregate:
    - task: py27
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: python
            tag: 2.7
        inputs:
          - name: source
        run:
          path: ci/test.sh
          args: ['-e', 'py27']
          dir: source

    - task: py35
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: python
            tag: 3.5
        inputs:
          - name: source
        run:
          path: ci/test.sh
          args: ['-e', 'py35']
          dir: source

    - task: py36
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: python
            tag: 3.6
        inputs:
          - name: source
        run:
          path: ci/test.sh
          args: ['-e', 'py36,flake8']
          dir: source

- name: maybe_release
  plan:
  - get: source
    trigger: true
    passed: [unit]

  - task: setup.py
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.6
      params:
        TWINE_USERNAME: ((twine_user))
        TWINE_PASSWORD: ((twine_pass))
      inputs:
        - name: source
      run:
        path: ci/release.sh
        dir: source
