---
resources:
  - name: source
    type: git
    source:
      uri: 'git@github.com:mattcl/ganttify.git'
      branch: master
      private_key: ((clone_key))

jobs:
- name: py27
  plan:
  - get: source
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 2.7
      inputs:
        - name: source
      run:
        path: ci/test.sh
        args: ['-e', 'py27']
        dir: source

- name: py35
  plan:
  - get: source
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.5
      inputs:
        - name: source
      run:
        path: ci/test.sh
        args: ['-e', 'py35']
        dir: source

- name: py36
  plan:
  - get: source
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.6
      inputs:
        - name: source
      run:
        path: ci/test.sh
        args: ['-e', 'py36,flake8']
        dir: source

- name: package
  plan:
  - get: source
    trigger: true
    passed: [py27, py35, py36]

  - task: setup.py
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: 'python:3.6'}
      inputs:
        - name: source
      run:
        path: ci/package.sh
        dir: source
